version: '3.4'

services:
  rabbitmq:
    image: rabbitmq
    build:
      context: packages/rabbit-mq
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
