// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ".keycloak__user-section__email-verified {\n  color: var(--pf-global--danger-color--100);\n}\n\nbutton.pf-c-button.pf-m-primary.kc-join-group-button {\n  margin-left: var(--pf-global--spacer--md);\n  margin-right: var(--pf-global--spacer--xl);\n}\n\n.kc-consents-chip-group .pf-c-chip-group,\nkc-consents-chip-group .pf-c-chip-group__list {\n  width: 100%;\n}\n\nbutton#kc-join-groups-button {\n  height: min-content;\n}\n\n.kc-join-group-modal-check {\n  margin-right: var(--pf-global--spacer--sm);\n}\n\n.join-group-dialog-row-disabled {\n  cursor: not-allowed;\n}\n\n.join-group-dialog-row-m-disabled {\n  pointer-events: none;\n  color: var(--pf-global--disabled-color--200);\n}\n\n.kc-who-will-appear-button {\n  margin-left: var(--pf-global--spacer--md);\n}\n\n.pf-c-chip.kc-consents-chip::before {\n  padding: 0px;\n  border: 0;\n}\n\n.pf-c-chip.kc-consents-chip {\n  padding: 0px;\n}\n\n.kc-consents-chip-group .pf-c-chip-group__list-item {\n  margin-right: 0px;\n}\n\n#consents-chip-text.pf-c-chip-text {\n  font-size: var(--pf-c-table--cell--FontSize);\n}\n\n.kc-consents-chip > .pf-c-chip__text {\n  font-size: var(--pf-c-table--cell--FontSize);\n  display: inline-block;\n}\n\n.pf-c-chip-group.kc-consents-chip-group\n  > div.pf-c-chip-group__main\n  > ul.pf-c-chip-group__list\n  li:first-child\n  .pf-c-chip__text::before {\n  content: \"\";\n}\n\n.pf-c-chip-group.kc-consents-chip-group\n  > div.pf-c-chip-group__main\n  > ul.pf-c-chip-group__list\n  .pf-c-chip__text::before {\n  content: \", \";\n}\n\ndiv.pf-c-chip-group.kc-consents-chip-group\n  > div.pf-c-chip-group__main\n  > ul.pf-c-chip-group__list\n  > li.pf-c-chip-group__list-item:last-child\n  > button.pf-c-chip.pf-m-overflow::before {\n  content: \"\";\n  margin-left: var(--pf-global--spacer--sm);\n}\n\ndiv.pf-c-chip-group.kc-consents-chip-group\n  > div.pf-c-chip-group__main\n  > ul.pf-c-chip-group__list\n  > li.pf-c-chip-group__list-item:last-child\n  > button.pf-c-chip.pf-m-overflow\n  > span::before {\n  content: \"\";\n  margin-left: var(--pf-global--spacer--sm);\n}\n\n.kc-search-users-text {\n  margin-left: var(--pf-global--spacer--md);\n  color: var(--pf-global--Color--400);\n}\n\narticle.pf-c-card.pf-m-flat.kc-linked-idps,\narticle.pf-c-card.pf-m-flat.kc-available-idps {\n  border: 0px;\n}\n\narticle.pf-c-card.pf-m-flat.kc-linked-idps > div > div > h1 {\n  margin-bottom: 0px;\n}\n\narticle.pf-c-card.pf-m-flat.kc-available-idps > div > div > h1 {\n  margin-bottom: 0px;\n}\n\n.kc-available-idps-text {\n  color: var(--pf-global--Color--200);\n}\n\n.kc-linked-idps-text {\n  color: var(--pf-global--Color--200);\n}\n\n.kc-no-providers-text {\n  text-align: center;\n}\n\n.keycloak__user-credentials__reset-form {\n  --pf-c-form--m-horizontal__group-label--md--GridColumnWidth: 13rem;\n}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}